name: Build and Artifact the ESP-IDF Project

on:
  push:
    tags:
     - 'v*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.1
          target: esp32
          path: '.'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/CLS.bin
          asset_name: cls-esp32-$tag.bin
          tag: ${{ github.ref }}
          overwrite: true
